spring.application.name=chatverse

spring.data.mongodb.uri=${MONGODB_URI}

server.port=8080

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile

app.cors.allowed-origins=${CORS_ORIGINS}